#if !canImport(ObjectiveC)
import XCTest

extension AttributedEnumIntrinsicTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AttributedEnumIntrinsicTest = [
        ("testEncode", testEncode),
    ]
}

extension AttributedIntrinsicTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AttributedIntrinsicTest = [
        ("testDecode", testDecode),
        ("testDecodePreview", testDecodePreview),
        ("testEncode", testEncode),
        ("testFooArray", testFooArray),
        ("testFooOptionalArray", testFooOptionalArray),
        ("testFooValueArray", testFooValueArray),
        ("testFooValueAttribute", testFooValueAttribute),
        ("testFooValueElement", testFooValueElement),
        ("testIntArray", testIntArray),
        ("testMixedArray", testMixedArray),
    ]
}

extension BenchmarkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BenchmarkTests = [
        ("testDecodeArrays", testDecodeArrays),
        ("testDecodeBools", testDecodeBools),
        ("testDecodeDatas", testDecodeDatas),
        ("testDecodeDates", testDecodeDates),
        ("testDecodeDecimals", testDecodeDecimals),
        ("testDecodeDictionaries", testDecodeDictionaries),
        ("testDecodeFloats", testDecodeFloats),
        ("testDecodeInts", testDecodeInts),
        ("testDecodeNulls", testDecodeNulls),
        ("testDecodeUInts", testDecodeUInts),
        ("testDecodeURLs", testDecodeURLs),
        ("testEncodeArrays", testEncodeArrays),
        ("testEncodeBools", testEncodeBools),
        ("testEncodeDatas", testEncodeDatas),
        ("testEncodeDates", testEncodeDates),
        ("testEncodeDecimals", testEncodeDecimals),
        ("testEncodeDictionaries", testEncodeDictionaries),
        ("testEncodeFloats", testEncodeFloats),
        ("testEncodeInts", testEncodeInts),
        ("testEncodeNulls", testEncodeNulls),
        ("testEncodeUInts", testEncodeUInts),
        ("testEncodeURLs", testEncodeURLs),
    ]
}

extension BooksTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BooksTest = [
        ("testBookXML", testBookXML),
        ("testCatalogXML", testCatalogXML),
    ]
}

extension BoolBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoolBoxTests = [
        ("testInvalidValues", testInvalidValues),
        ("testIsNull", testIsNull),
        ("testUnbox", testUnbox),
        ("testValidValues", testValidValues),
        ("testXMLString", testXMLString),
    ]
}

extension BoolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoolTests = [
        ("testAttribute", testAttribute),
        ("testElement", testElement),
        ("testMissing", testMissing),
    ]
}

extension BorderTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BorderTest = [
        ("testLeftBorder", testLeftBorder),
        ("testSingleEmpty", testSingleEmpty),
    ]
}

extension BoxTreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BoxTreeTests = [
        ("testNestedValues", testNestedValues),
    ]
}

extension BreakfastTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BreakfastTest = [
        ("testXML", testXML),
    ]
}

extension CDTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CDTest = [
        ("testXML", testXML),
    ]
}

extension ClassTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClassTests = [
        ("testEmpty", testEmpty),
    ]
}

extension DataBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataBoxTests = [
        ("testInvalidXMLStrings_base64", testInvalidXMLStrings_base64),
        ("testIsNull", testIsNull),
        ("testUnbox", testUnbox),
        ("testValidXMLStrings_base64", testValidXMLStrings_base64),
    ]
}

extension DataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataTests = [
        ("testAttribute", testAttribute),
        ("testElement", testElement),
        ("testKeyFormated", testKeyFormated),
        ("testKeyFormatedCouldNotDecodeError", testKeyFormatedCouldNotDecodeError),
        ("testKeyFormatedError", testKeyFormatedError),
        ("testKeyFormatedNoPathError", testKeyFormatedNoPathError),
        ("testMissing", testMissing),
        ("testStrategy", testStrategy),
    ]
}

extension DateBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DateBoxTests = [
        ("testInvalidStrings_formatter", testInvalidStrings_formatter),
        ("testInvalidStrings_iso8601", testInvalidStrings_iso8601),
        ("testInvalidStrings_millisecondsSince1970", testInvalidStrings_millisecondsSince1970),
        ("testInvalidStrings_secondsSince1970", testInvalidStrings_secondsSince1970),
        ("testIsNull", testIsNull),
        ("testUnbox", testUnbox),
        ("testValidStrings_formatter", testValidStrings_formatter),
        ("testValidStrings_iso8601", testValidStrings_iso8601),
        ("testValidStrings_millisecondsSince1970", testValidStrings_millisecondsSince1970),
        ("testValidStrings_secondsSince1970", testValidStrings_secondsSince1970),
    ]
}

extension DateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DateTests = [
        ("testAttribute", testAttribute),
        ("testElement", testElement),
        ("testKeyFormatedCouldNotDecodeError", testKeyFormatedCouldNotDecodeError),
        ("testKeyFormatedError", testKeyFormatedError),
        ("testKeyFormatedNoPathError", testKeyFormatedNoPathError),
        ("testMissing", testMissing),
    ]
}

extension DecimalBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecimalBoxTests = [
        ("testInvalidValues", testInvalidValues),
        ("testIsNull", testIsNull),
        ("testUnbox", testUnbox),
        ("testValidValues", testValidValues),
        ("testXMLString", testXMLString),
    ]
}

extension DecimalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecimalTests = [
        ("testAttribute", testAttribute),
        ("testElement", testElement),
        ("testMissing", testMissing),
    ]
}

extension DecodingContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecodingContainerTests = [
        ("testExample", testExample),
    ]
}

extension DynamicNodeDecodingTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicNodeDecodingTest = [
        ("testDecode", testDecode),
        ("testOverlappingKeys", testOverlappingKeys),
        ("testStrategyPriority", testStrategyPriority),
    ]
}

extension DynamicNodeEncodingTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicNodeEncodingTest = [
        ("testDecode", testDecode),
        ("testEncode", testEncode),
        ("testEncodeDecode", testEncodeDecode),
        ("testStrategyPriority", testStrategyPriority),
    ]
}

extension EmptyArrayTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EmptyArrayTest = [
        ("testEmptyArrayDecode", testEmptyArrayDecode),
        ("testWrappedEmptyArrayDecode", testWrappedEmptyArrayDecode),
        ("testWrappedEmptyDecode", testWrappedEmptyDecode),
        ("testWrappedOptionalEmptyDecode", testWrappedOptionalEmptyDecode),
    ]
}

extension EmptyElementEmptyStringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EmptyElementEmptyStringTests = [
        ("testArrayOfEmptyElementStringDecoding", testArrayOfEmptyElementStringDecoding),
        ("testEmptyElementEmptyStringDecoding", testEmptyElementEmptyStringDecoding),
        ("testEmptyElementEmptyStringWithAttributeDecoding", testEmptyElementEmptyStringWithAttributeDecoding),
        ("testExplicitlyNestedArrayOfEmptyElementEmptyStringDecoding", testExplicitlyNestedArrayOfEmptyElementEmptyStringDecoding),
        ("testNestedArrayOfEmptyElementEmptyStringDecoding", testNestedArrayOfEmptyElementEmptyStringDecoding),
        ("testNestedEmptyElementEmptyStringDecoding", testNestedEmptyElementEmptyStringDecoding),
    ]
}

extension EmptyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EmptyTests = [
        ("testAttribute", testAttribute),
        ("testElement", testElement),
    ]
}

extension EnumAssociatedValueTestComposite {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnumAssociatedValueTestComposite = [
        ("testDecodeArrayOfIntOrStringWrappers", testDecodeArrayOfIntOrStringWrappers),
        ("testDecodeIntOrStringWrapper", testDecodeIntOrStringWrapper),
        ("testEncodeArrayOfIntOrStringWrappers", testEncodeArrayOfIntOrStringWrappers),
        ("testEncodeIntOrStringWrapper", testEncodeIntOrStringWrapper),
    ]
}

extension ErrorContextTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorContextTest = [
        ("testErrorContext", testErrorContext),
        ("testErrorContextFirstLine", testErrorContextFirstLine),
        ("testErrorContextSizeOutsizeContent", testErrorContextSizeOutsizeContent),
    ]
}

extension FloatBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FloatBoxTests = [
        ("testInvalidValues", testInvalidValues),
        ("testIsNull", testIsNull),
        ("testUnbox", testUnbox),
        ("testValidValues", testValidValues),
        ("testXMLString", testXMLString),
    ]
}

extension FloatTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FloatTests = [
        ("testAttribute", testAttribute),
        ("testElement", testElement),
        ("testMissing", testMissing),
    ]
}

extension IntBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntBoxTests = [
        ("testInvalidValues", testInvalidValues),
        ("testIsNull", testIsNull),
        ("testUnbox", testUnbox),
        ("testValidValues", testValidValues),
        ("testXMLString", testXMLString),
    ]
}

extension IntTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntTests = [
        ("testAttribute", testAttribute),
        ("testElement", testElement),
        ("testMissing", testMissing),
    ]
}

extension KeyDecodingAndEncodingStrategyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyDecodingAndEncodingStrategyTests = [
        ("testCapitalized", testCapitalized),
        ("testKebabCase", testKebabCase),
    ]
}

extension KeyedBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyedBoxTests = [
        ("testDescription", testDescription),
        ("testIsNull", testIsNull),
        ("testSequence", testSequence),
        ("testSubscript", testSubscript),
        ("testUnbox", testUnbox),
        ("testXMLString", testXMLString),
    ]
}

extension KeyedIntTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyedIntTests = [
        ("testIntegerTypeAttribute", testIntegerTypeAttribute),
        ("testIntegerTypeElement", testIntegerTypeElement),
        ("testIntegerTypeMissing", testIntegerTypeMissing),
    ]
}

extension KeyedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyedTests = [
        ("testAttribute", testAttribute),
        ("testConvertFromSnakeCase", testConvertFromSnakeCase),
        ("testCustomDecoderConvert", testCustomDecoderConvert),
        ("testEmpty", testEmpty),
        ("testErrorDescriptionConvertFromSnakeCase", testErrorDescriptionConvertFromSnakeCase),
        ("testMultiElement", testMultiElement),
        ("testSingleElement", testSingleElement),
    ]
}

extension MixedContainerTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MixedContainerTest = [
        ("test", test),
    ]
}

extension NameSpaceTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NameSpaceTest = [
        ("testTable", testTable),
        ("testTableWithoutNamespaces", testTableWithoutNamespaces),
        ("testWorksheet", testWorksheet),
        ("testWorksheetWithoutNamespaces", testWorksheetWithoutNamespaces),
    ]
}

extension NestedAttributeChoiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NestedAttributeChoiceTests = [
        ("testNestedEnumsEncoding", testNestedEnumsEncoding),
    ]
}

extension NestedChoiceArrayTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NestedChoiceArrayTest = [
        ("testDecodingNestedChoiceArray", testDecodingNestedChoiceArray),
    ]
}

extension NestedChoiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NestedChoiceTests = [
        ("testBreakDecoding", testBreakDecoding),
        ("testEntriesDecoding", testEntriesDecoding),
        ("testNestedEnums", testNestedEnums),
        ("testNestedEnumsRoundTrip", testNestedEnumsRoundTrip),
        ("testNestedEnumsWithEmptyStruct", testNestedEnumsWithEmptyStruct),
        ("testParagraphDecoding", testParagraphDecoding),
        ("testPropertiesAsEntryDecoding", testPropertiesAsEntryDecoding),
        ("testPropertiesDecoding", testPropertiesDecoding),
        ("testRunAsEntryDecoding", testRunAsEntryDecoding),
        ("testRunDecoding", testRunDecoding),
    ]
}

extension NestingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NestingTests = [
        ("testDecodeKeyedWithinKeyed", testDecodeKeyedWithinKeyed),
        ("testDecodeKeyedWithinUnkeyed", testDecodeKeyedWithinUnkeyed),
        ("testDecodeUnkeyedWithinKeyed", testDecodeUnkeyedWithinKeyed),
        ("testDecodeUnkeyedWithinUnkeyed", testDecodeUnkeyedWithinUnkeyed),
        ("testEncodeKeyedWithinKeyed", testEncodeKeyedWithinKeyed),
        ("testEncodeKeyedWithinUnkeyed", testEncodeKeyedWithinUnkeyed),
        ("testEncodeUnkeyedWithinKeyed", testEncodeUnkeyedWithinKeyed),
        ("testEncodeUnkeyedWithinUnkeyed", testEncodeUnkeyedWithinUnkeyed),
    ]
}

extension NodeEncodingStrategyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NodeEncodingStrategyTests = [
        ("testItSortsKeysWhenEncodingAsAttributes", testItSortsKeysWhenEncodingAsAttributes),
        ("testItSortsKeysWhenEncodingAsElements", testItSortsKeysWhenEncodingAsElements),
        ("testKeyedContainer", testKeyedContainer),
        ("testSingleContainer", testSingleContainer),
        ("testUnkeyedContainer", testUnkeyedContainer),
    ]
}

extension NoteTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NoteTest = [
        ("testInvalidXML", testInvalidXML),
        ("testValidXML", testValidXML),
    ]
}

extension NullBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NullBoxTests = [
        ("testDescription", testDescription),
        ("testEqual", testEqual),
        ("testIsNull", testIsNull),
        ("testXMLString", testXMLString),
    ]
}

extension NullTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NullTests = [
        ("testAttribute", testAttribute),
        ("testElement", testElement),
    ]
}

extension OptionalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OptionalTests = [
        ("testMissing", testMissing),
    ]
}

extension PlantTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlantTest = [
        ("testXML", testXML),
    ]
}

extension QuoteDecodingTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QuoteDecodingTest = [
        ("testQuoteDecoding", testQuoteDecoding),
    ]
}

extension RJITest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RJITest = [
        ("testRSS", testRSS),
    ]
}

extension RelationshipsTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RelationshipsTest = [
        ("testDecoder", testDecoder),
    ]
}

extension RootLevelAttributeTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RootLevelAttributeTest = [
        ("testPolicyEncodingAtRoot", testPolicyEncodingAtRoot),
    ]
}

extension SharedBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SharedBoxTests = [
        ("testInit", testInit),
        ("testIsNull", testIsNull),
        ("testWithShared", testWithShared),
        ("testXMLString", testXMLString),
    ]
}

extension SimpleChoiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SimpleChoiceTests = [
        ("testIntOrStringArrayDecoding", testIntOrStringArrayDecoding),
        ("testIntOrStringArrayRoundTrip", testIntOrStringArrayRoundTrip),
        ("testIntOrStringDoubleArrayRoundTrip", testIntOrStringDoubleArrayRoundTrip),
        ("testIntOrStringIntDecoding", testIntOrStringIntDecoding),
        ("testIntOrStringRoundTrip", testIntOrStringRoundTrip),
        ("testIntOrStringStringDecoding", testIntOrStringStringDecoding),
    ]
}

extension SingleChildTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SingleChildTest = [
        ("testDecoder", testDecoder),
        ("testEncoder", testEncoder),
    ]
}

extension SpacePreserveTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpacePreserveTest = [
        ("testCopyright", testCopyright),
        ("testNestedOptional", testNestedOptional),
        ("testSimple", testSimple),
        ("testSimpleOptional", testSimpleOptional),
        ("testUntrimmed", testUntrimmed),
    ]
}

extension StringBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringBoxTests = [
        ("testInvalidValues", testInvalidValues),
        ("testIsNull", testIsNull),
        ("testUnbox", testUnbox),
        ("testValidValues", testValidValues),
        ("testXMLString", testXMLString),
    ]
}

extension StringExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringExtensionsTests = [
        ("testCapitalizingFirstLetter", testCapitalizingFirstLetter),
        ("testLowercasingFirstLetter", testLowercasingFirstLetter),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("testAttribute", testAttribute),
        ("testElement", testElement),
    ]
}

extension UIntBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UIntBoxTests = [
        ("testInvalidValues", testInvalidValues),
        ("testIsNull", testIsNull),
        ("testUnbox", testUnbox),
        ("testValidValues", testValidValues),
        ("testXMLString", testXMLString),
    ]
}

extension UIntTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UIntTests = [
        ("testAttribute", testAttribute),
        ("testElement", testElement),
        ("testMissing", testMissing),
    ]
}

extension URLBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLBoxTests = [
        ("testInvalidValues", testInvalidValues),
        ("testIsNull", testIsNull),
        ("testUnbox", testUnbox),
        ("testValidValues", testValidValues),
        ("testXMLString", testXMLString),
    ]
}

extension URLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLTests = [
        ("testAttribute", testAttribute),
        ("testElement", testElement),
        ("testMissing", testMissing),
    ]
}

extension UnkeyedBoxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnkeyedBoxTests = [
        ("testDescription", testDescription),
        ("testInsertAt", testInsertAt),
        ("testIsNull", testIsNull),
        ("testSequence", testSequence),
        ("testSubscript", testSubscript),
        ("testUnbox", testUnbox),
        ("testXMLString", testXMLString),
    ]
}

extension UnkeyedIntTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnkeyedIntTests = [
        ("testInts", testInts),
    ]
}

extension UnkeyedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnkeyedTests = [
        ("testAttribute", testAttribute),
        ("testEmpty", testEmpty),
        ("testMultiElement", testMultiElement),
        ("testNestedNilMultiElement", testNestedNilMultiElement),
        ("testNestedNilSingleElement", testNestedNilSingleElement),
        ("testNil", testNil),
        ("testNilNil", testNilNil),
        ("testSingleElement", testSingleElement),
    ]
}

extension XMLElementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLElementTests = [
        ("testInitKeyed", testInitKeyed),
        ("testInitNull", testInitNull),
        ("testInitSimple", testInitSimple),
        ("testInitUnkeyed", testInitUnkeyed),
    ]
}

extension XMLHeaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLHeaderTests = [
        ("testInit", testInit),
        ("testInitVersion", testInitVersion),
        ("testInitVersionEncoding", testInitVersionEncoding),
        ("testInitVersionEncodingStandalone", testInitVersionEncodingStandalone),
        ("testIsEmpty", testIsEmpty),
        ("testToXML", testToXML),
    ]
}

extension XMLKeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLKeyTests = [
        ("testInitIntValue", testInitIntValue),
        ("testInitStringValue", testInitStringValue),
        ("testInitStringValueIntValue", testInitStringValueIntValue),
    ]
}

extension XMLStackParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLStackParserTests = [
        ("testParseWith", testParseWith),
        ("testParseWithThrow", testParseWithThrow),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AttributedEnumIntrinsicTest.__allTests__AttributedEnumIntrinsicTest),
        testCase(AttributedIntrinsicTest.__allTests__AttributedIntrinsicTest),
        testCase(BenchmarkTests.__allTests__BenchmarkTests),
        testCase(BooksTest.__allTests__BooksTest),
        testCase(BoolBoxTests.__allTests__BoolBoxTests),
        testCase(BoolTests.__allTests__BoolTests),
        testCase(BorderTest.__allTests__BorderTest),
        testCase(BoxTreeTests.__allTests__BoxTreeTests),
        testCase(BreakfastTest.__allTests__BreakfastTest),
        testCase(CDTest.__allTests__CDTest),
        testCase(ClassTests.__allTests__ClassTests),
        testCase(DataBoxTests.__allTests__DataBoxTests),
        testCase(DataTests.__allTests__DataTests),
        testCase(DateBoxTests.__allTests__DateBoxTests),
        testCase(DateTests.__allTests__DateTests),
        testCase(DecimalBoxTests.__allTests__DecimalBoxTests),
        testCase(DecimalTests.__allTests__DecimalTests),
        testCase(DecodingContainerTests.__allTests__DecodingContainerTests),
        testCase(DynamicNodeDecodingTest.__allTests__DynamicNodeDecodingTest),
        testCase(DynamicNodeEncodingTest.__allTests__DynamicNodeEncodingTest),
        testCase(EmptyArrayTest.__allTests__EmptyArrayTest),
        testCase(EmptyElementEmptyStringTests.__allTests__EmptyElementEmptyStringTests),
        testCase(EmptyTests.__allTests__EmptyTests),
        testCase(EnumAssociatedValueTestComposite.__allTests__EnumAssociatedValueTestComposite),
        testCase(ErrorContextTest.__allTests__ErrorContextTest),
        testCase(FloatBoxTests.__allTests__FloatBoxTests),
        testCase(FloatTests.__allTests__FloatTests),
        testCase(IntBoxTests.__allTests__IntBoxTests),
        testCase(IntTests.__allTests__IntTests),
        testCase(KeyDecodingAndEncodingStrategyTests.__allTests__KeyDecodingAndEncodingStrategyTests),
        testCase(KeyedBoxTests.__allTests__KeyedBoxTests),
        testCase(KeyedIntTests.__allTests__KeyedIntTests),
        testCase(KeyedTests.__allTests__KeyedTests),
        testCase(MixedContainerTest.__allTests__MixedContainerTest),
        testCase(NameSpaceTest.__allTests__NameSpaceTest),
        testCase(NestedAttributeChoiceTests.__allTests__NestedAttributeChoiceTests),
        testCase(NestedChoiceArrayTest.__allTests__NestedChoiceArrayTest),
        testCase(NestedChoiceTests.__allTests__NestedChoiceTests),
        testCase(NestingTests.__allTests__NestingTests),
        testCase(NodeEncodingStrategyTests.__allTests__NodeEncodingStrategyTests),
        testCase(NoteTest.__allTests__NoteTest),
        testCase(NullBoxTests.__allTests__NullBoxTests),
        testCase(NullTests.__allTests__NullTests),
        testCase(OptionalTests.__allTests__OptionalTests),
        testCase(PlantTest.__allTests__PlantTest),
        testCase(QuoteDecodingTest.__allTests__QuoteDecodingTest),
        testCase(RJITest.__allTests__RJITest),
        testCase(RelationshipsTest.__allTests__RelationshipsTest),
        testCase(RootLevelAttributeTest.__allTests__RootLevelAttributeTest),
        testCase(SharedBoxTests.__allTests__SharedBoxTests),
        testCase(SimpleChoiceTests.__allTests__SimpleChoiceTests),
        testCase(SingleChildTest.__allTests__SingleChildTest),
        testCase(SpacePreserveTest.__allTests__SpacePreserveTest),
        testCase(StringBoxTests.__allTests__StringBoxTests),
        testCase(StringExtensionsTests.__allTests__StringExtensionsTests),
        testCase(StringTests.__allTests__StringTests),
        testCase(UIntBoxTests.__allTests__UIntBoxTests),
        testCase(UIntTests.__allTests__UIntTests),
        testCase(URLBoxTests.__allTests__URLBoxTests),
        testCase(URLTests.__allTests__URLTests),
        testCase(UnkeyedBoxTests.__allTests__UnkeyedBoxTests),
        testCase(UnkeyedIntTests.__allTests__UnkeyedIntTests),
        testCase(UnkeyedTests.__allTests__UnkeyedTests),
        testCase(XMLElementTests.__allTests__XMLElementTests),
        testCase(XMLHeaderTests.__allTests__XMLHeaderTests),
        testCase(XMLKeyTests.__allTests__XMLKeyTests),
        testCase(XMLStackParserTests.__allTests__XMLStackParserTests),
    ]
}
#endif
